version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - artlogic
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - artlogic
